name: New Algorithmist
favicon: null
layout_spectrum: 0.8717081651557237
typography_spectrum: 0.8842122829519212
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2488376412075013
  lightness: 0.027100928593426943
  saturation: 0.26055400911718607
  rhythmicContrast: 0.9248411655426025
purpose: []
